//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zongsoft.Scheduling.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zongsoft.Scheduling.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 总计 {0} 个触发器，{1} 个处理器。 的本地化字符串。
        /// </summary>
        internal static string Scheduler_Counting {
            get {
                return ResourceManager.GetString("Scheduler.Counting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}] {1}@{2} 处理完成  {3} 的本地化字符串。
        /// </summary>
        internal static string Scheduler_Handled {
            get {
                return ResourceManager.GetString("Scheduler.Handled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近执行时间：{0} 的本地化字符串。
        /// </summary>
        internal static string Scheduler_LastTime {
            get {
                return ResourceManager.GetString("Scheduler.LastTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示：按 Ctrl+C 键可退出侦听模式。 的本地化字符串。
        /// </summary>
        internal static string Scheduler_Listen_ToExit_Prompt {
            get {
                return ResourceManager.GetString("Scheduler.Listen.ToExit.Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进入 {0} 调度器侦听模式。 的本地化字符串。
        /// </summary>
        internal static string Scheduler_Listen_Welcome {
            get {
                return ResourceManager.GetString("Scheduler.Listen.Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下次执行时间：{0} 的本地化字符串。
        /// </summary>
        internal static string Scheduler_NextTime {
            get {
                return ResourceManager.GetString("Scheduler.NextTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未执行过 的本地化字符串。
        /// </summary>
        internal static string Scheduler_NoLastTime {
            get {
                return ResourceManager.GetString("Scheduler.NoLastTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不再执行 的本地化字符串。
        /// </summary>
        internal static string Scheduler_NoNextTime {
            get {
                return ResourceManager.GetString("Scheduler.NoNextTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行完成，累计 {0} 个处理器被调用。 的本地化字符串。
        /// </summary>
        internal static string Scheduler_Occurred {
            get {
                return ResourceManager.GetString("Scheduler.Occurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 累计重试 {0} 次，最近一次：{1} 的本地化字符串。
        /// </summary>
        internal static string Scheduler_Retry_Counting {
            get {
                return ResourceManager.GetString("Scheduler.Retry.Counting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 截止于：{0} 的本地化字符串。
        /// </summary>
        internal static string Scheduler_Retry_Expiration {
            get {
                return ResourceManager.GetString("Scheduler.Retry.Expiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重试失败：{0}@{1} 累计重试 {2) 次，最近一次：{3} 的本地化字符串。
        /// </summary>
        internal static string Scheduler_Retry_Failed {
            get {
                return ResourceManager.GetString("Scheduler.Retry.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首次重试 的本地化字符串。
        /// </summary>
        internal static string Scheduler_Retry_First {
            get {
                return ResourceManager.GetString("Scheduler.Retry.First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重试成功： 的本地化字符串。
        /// </summary>
        internal static string Scheduler_Retry_Succeed {
            get {
                return ResourceManager.GetString("Scheduler.Retry.Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *无重试期限* 的本地化字符串。
        /// </summary>
        internal static string Scheduler_Retry_Unlimited {
            get {
                return ResourceManager.GetString("Scheduler.Retry.Unlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调度完成，累计 {0} 个处理被调度，触发器列表： 的本地化字符串。
        /// </summary>
        internal static string Scheduler_Scheduled {
            get {
                return ResourceManager.GetString("Scheduler.Scheduled", resourceCulture);
            }
        }
    }
}
